CREATE TABLE categories (
  category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR2(50) NOT NULL UNIQUE,
  description   VARCHAR2(200)
);

-- 2. PRODUCTS
CREATE TABLE products (
  product_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR2(100) NOT NULL,
  description    VARCHAR2(255),
  category_id    NUMBER NOT NULL,
  unit_price     NUMBER(10,2) NOT NULL CHECK (unit_price >= 0),
  stock_quantity NUMBER DEFAULT 0 CHECK (stock_quantity >= 0),
  image_url      VARCHAR2(200),
  CONSTRAINT fk_product_category FOREIGN KEY (category_id)
    REFERENCES categories(category_id)
);

-- 3. CUSTOMERS
CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(100) NOT NULL,
  email       VARCHAR2(150) UNIQUE,
  phone       VARCHAR2(20),
  address     VARCHAR2(255)
);

-- 4. ORDERS
CREATE TABLE orders (
  order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  NUMBER NOT NULL,
  order_date   DATE DEFAULT SYSDATE NOT NULL,
  status       VARCHAR2(20) DEFAULT 'PENDING'
               CHECK (status IN ('PENDING','APPROVED','SHIPPED','COMPLETED','CANCELLED')),
  total_amount NUMBER(12,2),
  CONSTRAINT fk_order_customer FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

-- 5. ORDER_ITEMS
CREATE TABLE order_items (
  order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      NUMBER NOT NULL,
  product_id    NUMBER NOT NULL,
  quantity      NUMBER NOT NULL CHECK (quantity > 0),
  price_each    NUMBER(10,2) NOT NULL CHECK (price_each >= 0),
  CONSTRAINT fk_item_order FOREIGN KEY (order_id)
    REFERENCES orders(order_id),
  CONSTRAINT fk_item_product FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

-- 6. APP_USERS
CREATE TABLE app_users (
  user_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username   VARCHAR2(50) UNIQUE NOT NULL,
  full_name  VARCHAR2(100),
  role       VARCHAR2(20) NOT NULL CHECK (role IN ('ADMIN','EMPLOYEE','MANAGER'))
);

-- Helpful indexes (optional but good)
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);

-- ============================================
-- 2) SEED DATA (APPLE)
-- ============================================

-- Categories
INSERT INTO categories (category_name, description) VALUES ('iPhone', 'Apple smartphones');
INSERT INTO categories (category_name, description) VALUES ('MacBook', 'Apple laptops');
INSERT INTO categories (category_name, description) VALUES ('iPad', 'Apple tablets');
INSERT INTO categories (category_name, description) VALUES ('Apple Watch', 'Apple smartwatches');
INSERT INTO categories (category_name, description) VALUES ('AirPods', 'Apple wireless earbuds');
INSERT INTO categories (category_name, description) VALUES ('Accessories', 'Apple accessories');

-- Products (NO hardcoded category_id)
-- iPhones
INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('iPhone 15 Pro Max', '256GB, Titanium',
        (SELECT category_id FROM categories WHERE category_name='iPhone'),
        1199, 15, 'iphone_15_pro_max.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('iPhone 15 Pro', '128GB, Space Black',
        (SELECT category_id FROM categories WHERE category_name='iPhone'),
        999, 20, 'iphone_15_pro.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('iPhone 15', '128GB, Blue',
        (SELECT category_id FROM categories WHERE category_name='iPhone'),
        799, 25, 'iphone_15.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('iPhone 14', '128GB, Purple',
        (SELECT category_id FROM categories WHERE category_name='iPhone'),
        699, 12, 'iphone_14.png');

-- MacBooks
INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('MacBook Pro 16"', 'M3 Max, 36GB RAM, 1TB SSD',
        (SELECT category_id FROM categories WHERE category_name='MacBook'),
        3499, 8, 'mbp_16.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('MacBook Pro 14"', 'M3 Pro, 18GB RAM, 512GB SSD',
        (SELECT category_id FROM categories WHERE category_name='MacBook'),
        1999, 10, 'mbp_14.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('MacBook Air 15"', 'M2, 8GB RAM, 256GB SSD',
        (SELECT category_id FROM categories WHERE category_name='MacBook'),
        1299, 18, 'mba_15.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('MacBook Air 13"', 'M2, 8GB RAM, 256GB SSD',
        (SELECT category_id FROM categories WHERE category_name='MacBook'),
        1099, 22, 'mba_13.png');

-- iPads
INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('iPad Pro 12.9"', 'M2, 256GB, WiFi',
        (SELECT category_id FROM categories WHERE category_name='iPad'),
        1099, 12, 'ipad_pro_12_9.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('iPad Air', 'M1, 64GB, WiFi',
        (SELECT category_id FROM categories WHERE category_name='iPad'),
        599, 15, 'ipad_air.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('iPad 10th Gen', '64GB, WiFi',
        (SELECT category_id FROM categories WHERE category_name='iPad'),
        449, 20, 'ipad_10th.png');

-- Apple Watch
INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('Apple Watch Ultra 2', '49mm, Titanium',
        (SELECT category_id FROM categories WHERE category_name='Apple Watch'),
        799, 10, 'watch_ultra_2.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('Apple Watch Series 9', '45mm, Aluminum',
        (SELECT category_id FROM categories WHERE category_name='Apple Watch'),
        429, 18, 'watch_s9.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('Apple Watch SE', '44mm, Aluminum',
        (SELECT category_id FROM categories WHERE category_name='Apple Watch'),
        279, 25, 'watch_se.png');

-- AirPods
INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('AirPods Pro 2', 'USB-C, Active Noise Cancellation',
        (SELECT category_id FROM categories WHERE category_name='AirPods'),
        249, 30, 'airpods_pro_2.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('AirPods 3', 'Spatial Audio',
        (SELECT category_id FROM categories WHERE category_name='AirPods'),
        169, 35, 'airpods_3.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('AirPods Max', 'Over-ear, Space Gray',
        (SELECT category_id FROM categories WHERE category_name='AirPods'),
        549, 8, 'airpods_max.png');

-- Accessories
INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('Magic Keyboard', 'with Touch ID',
        (SELECT category_id FROM categories WHERE category_name='Accessories'),
        149, 40, 'magic_keyboard.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('Magic Mouse', 'Multi-Touch Surface',
        (SELECT category_id FROM categories WHERE category_name='Accessories'),
        79, 45, 'magic_mouse.png');

INSERT INTO products (name, description, category_id, unit_price, stock_quantity, image_url)
VALUES ('USB-C Cable', '1m',
        (SELECT category_id FROM categories WHERE category_name='Accessories'),
        19, 100, 'usb_c_cable.png');

-- Customers
INSERT INTO customers (name, email, phone, address)
VALUES ('John Smith', 'john.smith@email.com', '555-0101', '123 Apple St, Cupertino, CA');

INSERT INTO customers (name, email, phone, address)
VALUES ('Sarah Johnson', 'sarah.j@email.com', '555-0102', '456 Tech Ave, San Francisco, CA');

INSERT INTO customers (name, email, phone, address)
VALUES ('Michael Chen', 'mchen@email.com', '555-0103', '789 Innovation Blvd, Palo Alto, CA');

INSERT INTO customers (name, email, phone, address)
VALUES ('Emily Davis', 'emily.davis@email.com', '555-0104', '321 Valley Rd, San Jose, CA');

-- ============================================
-- 3) DEMO ORDERS (GENERAL / SAFE using RETURNING)
-- ============================================

DECLARE
  v_order_id NUMBER;
BEGIN
  -- Order A: Sarah buys MacBook Pro 14" + AirPods Pro 2
  INSERT INTO orders (customer_id, order_date, status, total_amount)
  VALUES ((SELECT customer_id FROM customers WHERE email='sarah.j@email.com'),
          SYSDATE - 10, 'COMPLETED', NULL)
  RETURNING order_id INTO v_order_id;

  INSERT INTO order_items (order_id, product_id, quantity, price_each)
  VALUES (v_order_id, (SELECT product_id FROM products WHERE name='MacBook Pro 14"'), 1,
          (SELECT unit_price FROM products WHERE name='MacBook Pro 14"'));

  INSERT INTO order_items (order_id, product_id, quantity, price_each)
  VALUES (v_order_id, (SELECT product_id FROM products WHERE name='AirPods Pro 2'), 1,
          (SELECT unit_price FROM products WHERE name='AirPods Pro 2'));

  UPDATE orders
  SET total_amount = (SELECT SUM(quantity * price_each) FROM order_items WHERE order_id = v_order_id)
  WHERE order_id = v_order_id;

  -- Order B: John buys iPad Pro 12.9"
  INSERT INTO orders (customer_id, order_date, status, total_amount)
  VALUES ((SELECT customer_id FROM customers WHERE email='john.smith@email.com'),
          SYSDATE - 5, 'SHIPPED', NULL)
  RETURNING order_id INTO v_order_id;

  INSERT INTO order_items (order_id, product_id, quantity, price_each)
  VALUES (v_order_id, (SELECT product_id FROM products WHERE name='iPad Pro 12.9"'), 1,
          (SELECT unit_price FROM products WHERE name='iPad Pro 12.9"'));

  UPDATE orders
  SET total_amount = (SELECT SUM(quantity * price_each) FROM order_items WHERE order_id = v_order_id)
  WHERE order_id = v_order_id;

  -- Order C: Michael buys AirPods Max
  INSERT INTO orders (customer_id, order_date, status, total_amount)
  VALUES ((SELECT customer_id FROM customers WHERE email='mchen@email.com'),
          SYSDATE - 2, 'PENDING', NULL)
  RETURNING order_id INTO v_order_id;

  INSERT INTO order_items (order_id, product_id, quantity, price_each)
  VALUES (v_order_id, (SELECT product_id FROM products WHERE name='AirPods Max'), 1,
          (SELECT unit_price FROM products WHERE name='AirPods Max'));

  UPDATE orders
  SET total_amount = (SELECT SUM(quantity * price_each) FROM order_items WHERE order_id = v_order_id)
  WHERE order_id = v_order_id;

  -- Order D: Emily buys iPhone 15 Pro + Apple Watch Series 9
  INSERT INTO orders (customer_id, order_date, status, total_amount)
  VALUES ((SELECT customer_id FROM customers WHERE email='emily.davis@email.com'),
          SYSDATE - 1, 'PENDING', NULL)
  RETURNING order_id INTO v_order_id;

  INSERT INTO order_items (order_id, product_id, quantity, price_each)
  VALUES (v_order_id, (SELECT product_id FROM products WHERE name='iPhone 15 Pro'), 1,
          (SELECT unit_price FROM products WHERE name='iPhone 15 Pro'));

  INSERT INTO order_items (order_id, product_id, quantity, price_each)
  VALUES (v_order_id, (SELECT product_id FROM products WHERE name='Apple Watch Series 9'), 1,
          (SELECT unit_price FROM products WHERE name='Apple Watch Series 9'));

  UPDATE orders
  SET total_amount = (SELECT SUM(quantity * price_each) FROM order_items WHERE order_id = v_order_id)
  WHERE order_id = v_order_id;

  COMMIT;
END;
/
-- Users
INSERT INTO app_users (username, full_name, role) VALUES ('admin', 'Admin User', 'ADMIN');
INSERT INTO app_users (username, full_name, role) VALUES ('employee1', 'Store Employee', 'EMPLOYEE');
INSERT INTO app_users (username, full_name, role) VALUES ('manager1', 'Store Manager', 'MANAGER');

COMMIT;
